sudo: required

services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
  - echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
  - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
  - echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
  - sudo apt-get update && sudo apt-get install google-cloud-sdk
    
install: 
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - sudo apt-get install -y kubectl
  - gcloud auth activate-service-account --key-file service-account.json --quiet
  - gcloud components install gke-gcloud-auth-plugin
  - gke-gcloud-auth-plugin --version
  - export USE_GKE_GCLOUD_AUTH_PLUGIN=True
  - gcloud config set project multi-container-k8s-410914
  - gcloud config set compute/zone asia-south2-a
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t majinbisht/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true majinbisht/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master